### ISSUE TITLE
/bin/sh: ip: command not found     [!] Cannot get your local IP addres, please write it: 

### ISSUE THREAD

**Issue by GoogleSmileMa** [Trackbool/DerpNSpoof#2]
![image](https://user-images.githubusercontent.com/31458648/39240481-786bc28e-48b6-11e8-84b5-76e59073c6fa.png)
why?

**Comment by Trackbool** [comment]
The tool tries to get your local IP address using an internal command. If it´s not possible, it will ask you to enter it manually.
When I have a free time, I'll fix it. Thanks!
