### ISSUE TITLE
No Module Named `scapy`

### ISSUE THREAD

**Issue by dssecret** [Trackbool/DerpNSpoof#4]
When I ran DerpNSpoof, it gave me the error `ImportError: No module named scapy`. Then I went on to ad `/lib/bin/`, `/lib/local/lib/python2.7/site-packages/`, and `/usr/local/lib/python3.5/site-packages` as recommended by [this SO question](https://stackoverflow.com/questions/46602880/importerror-no-module-named-scapy-all). Yet, DerpNSpoof, still doesn't work. Additionally, I looked at Issue #1 and verified that I downloaded `scapy` not `scapy-python3`.

**Comment by CJSparrow** [comment]
```pip install scapy```
you might have more than python in ur PC

**Comment by testhaha1234** [comment]
it is  a python3 script it might be `pip3 install scapy`
